### ISSUE TITLE
[BUG] Exception while creating PDO object:could not find driver

### ISSUE THREAD

**Issue by jacroe** [HenryQW/Awesome-TTRSS#240] opened 2021-01-17 11:04 UTC
**Describe the bug**
On pulling the latest image and starting up, multiple error messages appear in the logs

**Have you googled?**
Yes and I haven't immediately found anything.

**Deployment method**
 - Docker or docker-compose: docker-compose
 - Version of the image used [e.g. latest, nightly, 19.8]: The error appears in `latest` and does not appear in `nightly-2021-01-15`

**Deployment environment**
 - OS: Raspbian 10 (buster)
 - Browser: Chrome (on a different machine)

**To Reproduce**
1. Use the attached `docker-compose.yml` file.
2. Run `docker-compose up`
3. See the error messages.

**Expected behavior**
A normal runtime

**Screenshots**
N/A

**Error logs**
```
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[09:01:12/624] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[04:19:36/627] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[07:03:52/630] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[13:00:08/633] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[08:35:36/636] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
[01:41:44/639] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
[13:34:16/642] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
[04:30:16/645] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
[06:53:12/648] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
[06:53:12/651] Spawn interval: 120 sec
<pre>Exception while creating PDO object:could not find driver</pre>s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-supervise php-fpm: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
```

**Comment by jacroe** [comment] 2021-01-17 11:05
[docker-compose.yaml.txt](https://github.com/HenryQW/Awesome-TTRSS/files/5825911/docker-compose.yaml.txt)

**Comment by HenryQW** [comment] 2021-01-17 13:50
My server has been running latest for 26 hours without a problem.

**Comment by elmagnificogi** [comment] 2021-01-18 03:18
> My server has been running latest for 26 hours without a problem.

i have the same problem with latest version

**Comment by elmagnificogi** [comment] 2021-01-18 04:11
> My server has been running latest for 26 hours without a problem.

same problem

**Comment by elmagnificogi** [comment] 2021-01-18 04:12
```
postgres             | waiting for server to start....2021-01-18 04:10:17.587 UTC [35] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres             | 2021-01-18 04:10:17.593 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres             | 2021-01-18 04:10:17.604 UTC [36] LOG:  database system was shut down at 2021-01-18 04:10:16 UTC
postgres             | 2021-01-18 04:10:17.609 UTC [35] LOG:  database system is ready to accept connections
postgres             |  done
postgres             | server started
postgres             | 
postgres             | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres             | 
postgres             | waiting for server to shut down....2021-01-18 04:10:17.687 UTC [35] LOG:  received fast shutdown request
postgres             | 2021-01-18 04:10:17.699 UTC [35] LOG:  aborting any active transactions
postgres             | 2021-01-18 04:10:17.700 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
postgres             | 2021-01-18 04:10:17.700 UTC [37] LOG:  shutting down
postgres             | 2021-01-18 04:10:17.724 UTC [35] LOG:  database system is shut down
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:17/24] Spawn interval: 120 sec
postgres             |  done
postgres             | server stopped
postgres             | 
postgres             | PostgreSQL init process complete; ready for start up.
postgres             | 
postgres             | 2021-01-18 04:10:17.812 UTC [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres             | 2021-01-18 04:10:17.812 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres             | 2021-01-18 04:10:17.812 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres             | 2021-01-18 04:10:17.825 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres             | 2021-01-18 04:10:17.841 UTC [47] LOG:  database system was shut down at 2021-01-18 04:10:17 UTC
postgres             | 2021-01-18 04:10:17.849 UTC [1] LOG:  database system is ready to accept connections
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:18/27] Spawn interval: 120 sec
mercury              | ??Mercury Parser API listens on port 3000
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:19/30] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:20/33] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:21/36] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:22/39] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:23/42] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:24/45] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:25/48] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:26/51] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:27/54] Spawn interval: 120 sec
ttrss                | <pre>Exception while creating PDO object:could not find driver</pre>[04:10:28/57] Spawn interval: 120 sec

```

**Comment by elmagnificogi** [comment] 2021-01-18 06:41
用其他编排文件就是正确的，用默认的就报错

**Comment by oppilate** [comment] 2021-01-21 12:25
Probably you need to restart the postgres container or the ttrss container. Sometimes it's because fatals in the postges container, or the ttrss container finishes its initialization before the postgres container (which spends plenty of time to startup)

**Comment by elmagnificogi** [comment] 2021-01-21 13:17
@oppilate, In face,there is a wait.sh for that , it will wait the postgres startup.

**Comment by oppilate** [comment] 2021-01-21 23:08
> @oppilate, In face,there is a wait.sh for that , it will wait the postgres startup.

Yes. So it should be the later case. But I encountered this today and fixed the problem by restarting the postgres container (the former case)

**Comment by tuzi3040** [comment] 2021-01-22 05:19
> 莫名其妙出现了全部url无法解析host，但是我试过了ping的通，其他也没问题，但是全部联机都无法解析host

What's your docker version? There maybe some network issue with docker-ce(moby) > 20.10.0, see moby/moby#41775.
It looks like docker-ce starting to use `firewalld` to configure the network instead of `iptable` since version 20.10.0.
You may downgrade docker-ce to major version 19(like I did and which did resolve the domain resolve issue), or try something related to firewalld.

My issue mainly prints `127.0.0.1:<some port>->127.0.0.11:53: connection refused`, which is a kind of dns failure, results in application error. After downgrading to major version 19, the problem gone.

**Comment by elmagnificogi** [comment] 2021-01-22 11:36
@tuzi3040, my docker has run 7 months, then one day it suddenly cant resolve host,restart or docker-compose down cant solve it. so i update it to the new version

**Comment by tuzi3040** [comment] 2021-01-22 12:00
> @tuzi3040, my docker has run 7 months, then one day it suddenly cant resolve host,restart or docker-compose down cant solve it. so i update it to the new version

Depending on the version of os and docker you use, there can be some network (or dns) issues.
Docker 20.10 do fix some network issues related to CentOS 8 and RHEL 8. [Docker 20.10 release notes](https://docs.docker.com/engine/release-notes/)

**Comment by mbentley** [comment] 2021-01-22 12:33
I have noticed the same behavior but on a different project of mine (https://github.com/mbentley/docker-timemachine) that is using `alpine:latest`.  Alpine Linux recently release 3.13 and I see the same sort of behavior but only for armv7l images.  My normal x86/amd64 images work fine.  I temporarily switched back to Alpine 3.12 and everything is working fine.

**Comment by jacroe** [comment] 2021-01-22 12:39
@mbentley that's probably a good lead because my RPi 4is using armv7l images for this.

**Comment by mbentley** [comment] 2021-01-22 13:34
FYI, I filed an issue with Alpine Linux: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12346

**Comment by HenryQW** [comment] 2021-01-23 16:45
Thank you for posting this. @mbentley

Sorry for the late response, been really busy recently. I have pushed a temporary fix for this.

I will keep the issue open until the root cause is sorted.

**Comment by oppilate** [comment] 2021-01-25 10:30
Well, I believe it has nothing to do with alpine. If you start tt-rss only after `database system is ready to accept connections` is shown in postgres, everything will be fine. The problem is, `Awesome-TTRSS` checks for whether the port is available, while postgresql does some other work after the ports are open. If you attempt to access the database before it's ready, it may cause a `FATAL:  the database system is starting up`

**Comment by oppilate** [comment] 2021-01-25 10:35
A short solution could be waiting for health condition by docker-compose: https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1

**Comment by oppilate** [comment] 2021-01-25 10:45
Another solution is to use a [postgres-oriented `wait-for` script ](https://docs.docker.com/compose/startup-order/):
````shell
#!/bin/sh
# wait-for-postgres.sh

set -e
  
host="$1"
shift
cmd="$@"
  
until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$host" -U "postgres" -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done
  
>&2 echo "Postgres is up - executing command"
exec $cmd

````

**Closed** 2021-02-19 16:17 UTC
Labels: bug
