### ISSUE TITLE
[BUG] ttrss 连接到了错误的 socket 地址导致无法正确连接数据库

### ISSUE THREAD

**Issue by wxxb789** [HenryQW/Awesome-TTRSS#269] opened 2021-02-25 06:24 UTC
**Bug 描述**
 ttrss 连接到了错误的 socket 地址导致无法正确连接数据库

**部署方法**
 - docker-compose
 - latest
 - 但是使用的是 pg12，使用pg13一样也有错误

**部署环境**
 - debian

**复现步骤**
执行`docker-compose up`报错

**截屏**
![Snipaste_2021-02-25_14-19-52](https://user-images.githubusercontent.com/49564443/109112143-1dd04700-7775-11eb-8c3e-107b99002a70.png)

**Comment by oppilate** [comment] 2021-02-25 06:37
True because https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337

I'm thinking about just basing on the upstream's docker image: https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/static-dockerhub/README.md. Anyway, we are just adding some plugins

**Comment by wxxb789** [comment] 2021-02-25 06:42
Got it. 
And is there any previous stable versions of ttrss docker image?

**Comment by oppilate** [comment] 2021-02-25 08:15
> Got it.
> And is there any previous stable versions of ttrss docker image?

Just realize it's already answered: https://github.com/HenryQW/Awesome-TTRSS/issues/267#issuecomment-784246758

**Comment by HenryQW** [comment] 2021-02-25 13:30
Duplicate of #267

**Closed by HenryQW** 2021-02-25 13:30 UTC
Labels: bug

**Comment by HenryQW** [comment] 2021-02-25 13:37
> True because https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337
> 
> 
> 
> I'm thinking about just basing on the upstream's docker image: https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/static-dockerhub/README.md. Anyway, we are just adding some plugins.
> 
> 
> 
> S6 is not that worth to insist on.

I thought about that too, but the upstream docker uses git to periodically pull master branch. Then the master branch releases too many breaking changes (albeit fox usually realizes problems pretty soon and pushes another fix commit). at least we can revert back to a stable tag rather than manually checkout commit, which is not intuitive to novice users.

**Comment by HenryQW** [comment] 2021-02-25 13:39
Without a release system, third party plugins also tend to lag behind, so clinging on to a stable image is a better approach to me.

**Comment by proletarius101** [comment] 2021-02-26 01:17
> Without a release system, third party plugins also tend to lag behind, so clinging on to a stable image is a better approach to me.

You may let a testing branch fetch the latest commit, and manually push it to to the stable branch when plugins fix their problems
